#!/usr/bin/perl

#
#  Note this file was automacially generated by the GFS
#    prgram make_perl_formatter. You should modified this file
#    only under unusual circumstances.
#

use FindBin qw($Bin);   # Find directory where this script was executed.
use lib "$Bin/../perllib";     # Add library directory to lib path.
use GFS_format;

parse_args(@ARGV);

sub MISSING {
  "-99"
;
}

sub FCT_HOUR {
  TIME_FORMAT("%m/%d/%Y,%H")

;
}

sub TYPE {
  TIME_OFFSET() > CURRENT_TIME_OFFSET() ? "F" : "O"

;
}

sub heat {
  HEAT_INDEX_F("%.0f", MISSING())

;
}

sub chill {
  WIND_CHILL_F("%.0f", MISSING())

;
}

sub QPF {
  FORMAT("%.2f", QPF03_I("%.2f", "0.00")/3)

;
}

sub print_record_USER_DATA_HEADER {
  send_output "ICAO,DATE,HOUR,InstTemperature,InstDewPoint\n";
}

sub print_record_USER_DATA {
  send_output STATION_ICAO();
  send_output TEXT(",");
  send_output FCT_HOUR();
  send_output TEXT(",");
  send_output TEMP_F("%.0f", MISSING());
  send_output TEXT(",");
  send_output DEW_F("%.0f", MISSING());
  send_output "\n";
}

sub print_header_1 {
}

sub print_footer_1 {
}

sub generate {
  print_header_1;
  $start_loop_0 = $min_station_idx;
  $end_loop_0 = $max_station_idx;
  $incr_loop_0 = $step_station_idx;
  if ($incr_loop_0 == 0)
  {
    $end_loop_0 = $start_loop_0 - 1;
  }
  $save_loop_0 = $station_idx;
  for ($station_idx = $start_loop_0;
    $incr_loop_0 > 0 ? $station_idx <= $end_loop_0 : $station_idx >= $end_loop_0;
    $station_idx += $incr_loop_0)
  {
    $start_loop_1 = LOCAL_DAY_HOUR(0, 0) ;
    $end_loop_1 =  LOCAL_DAY_HOUR(14, 23) ;
    $incr_loop_1 =  HOUR_STEP(1);
    if ($incr_loop_1 == 0)
    {
      $end_loop_1 = $start_loop_1 - 1;
    }
    $save_loop_1 = $time_offset_sec;
    for ($time_offset_sec = $start_loop_1;
      $incr_loop_1 > 0 ? $time_offset_sec <= $end_loop_1 : $time_offset_sec >= $end_loop_1;
      $time_offset_sec += $incr_loop_1)
    {
      print_record_USER_DATA;
    }
    $time_offset_sec = $save_loop_1;
  }
  $station_idx = $save_loop_0;
  print_footer_1;
}

start_first_pass;
generate;
start_second_pass;
generate;
